kind: Deployment
apiVersion: apps/v1
metadata:
  name: mypythonapp
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/mypythonapp
  uid: 464c0047-8cc5-11ea-aee1-42010a800083
  resourceVersion: '283242'
  generation: 3
  creationTimestamp: '2020-05-02T22:35:50Z'
  labels:
    app: mypythonapp
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypythonapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mypythonapp
    spec:
      containers:
        - name: mypythonapp
          image: 'gcr.io/devop-manu/mypythonapp:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-05-02T22:48:08Z'
      lastTransitionTime: '2020-05-02T22:48:08Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-05-02T22:48:08Z'
      lastTransitionTime: '2020-05-02T22:35:50Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "mypythonapp-54f7d96dc4" has successfully progressed.
